version: "3.8"

services:
  vpn-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swaga_vpn_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - bot_data:/app/backups
      - ./vpn_bot.db:/app/vpn_bot.db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot_data:
